// <auto-generated />
using System;
using Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240816201840_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Domain.Entities.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "George Lucas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Juan José Campanella"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdDirector")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdDirector");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Durante la Segunda Guerra Mundial, el teniente general Leslie Groves designa al físico J. Robert Oppenheimer para un grupo de trabajo que está desarrollando el Proyecto Manhattan, cuyo objetivo consiste en fabricar la primera bomba atómica.",
                            IdDirector = 1,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjVhNGYyMTktNWU0Yi00YjQwLWJmYTQtNDJmODliOTE0NmY5XkEyXkFqcGdeQXVyMTQ4NTgxNzYx._V1_FMjpg_UX880_.jpg",
                            Name = "Oppenheimer",
                            Origin = "Internacional"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gracias a un descubrimiento, un grupo de científicos y exploradores, encabezados por Cooper, se embarcan en un viaje espacial para encontrar un lugar con las condiciones necesarias para reemplazar a la Tierra y comenzar una nueva vida allí.",
                            IdDirector = 1,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UY3600_.jpg",
                            Name = "Interestelar",
                            Origin = "Internacional"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Dom Cobb es un ladrón con una extraña habilidad para entrar a los sueños de la gente y robarles los secretos de sus subconscientes. Su habilidad lo ha vuelto muy popular en el mundo del espionaje corporativo, pero ha tenido un gran costo en la gente que ama. Cobb obtiene la oportunidad de redimirse cuando recibe una tarea imposible: plantar una idea en la mente de una persona. Si tiene éxito, será el crimen perfecto, pero un enemigo se anticipa a sus movimientos.",
                            IdDirector = 1,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTUzMzUyOTktNmYyNS00YTA1LWIxNmQtMGIzZDYxZGI3OTliXkEyXkFqcGdeQXVyMTYzMDM0NTU@.V1_FMjpg_UY2812.jpg",
                            Name = "El origen",
                            Origin = "Internacional"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Obi-Wan Kenobi es un joven aprendiz caballero Jedi bajo la tutela de Qui-Gon Jinn; Anakin Skywalker, quien después será padre de Luke Skywalker y se convertirá en Darth Vader, solamente es un niño de 9 años. Cuando la Federación de Comercio corta todas las rutas al planeta Naboo, Qui-Gon y Obi-Wan son asignados para solucionar el problema.",
                            IdDirector = 2,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZWYwZDZjMmQtZGYzZC00MzhkLWE4MDYtMDg0ZGQ4MmU3YjRlXkEyXkFqcGdeQXVyNzA4ODc3ODU@._V1_FMjpg_UX398_.jpg",
                            Name = "Star Wars: episodio I",
                            Origin = "Internacional"
                        },
                        new
                        {
                            Id = 5,
                            Description = "En el Senado Galáctico reina la inquietud. Varios miles de sistemas solares han declarado su intención de abandonar la República. La reina Amidala regresa al Senado para conseguir un ejército que ayude a los caballeros jedi.",
                            IdDirector = 2,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYTAzNjA4ZDMtNTZmNi00MDg2LTg4NzctNGI4NDYyMDMyZmNjXkEyXkFqcGdeQXVyNzExODc3Nzk@._V1_FMjpg_UX871_.jpg",
                            Name = "Star Wars: episodio II",
                            Origin = "Internacional"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Seducido por el lado oscuro, Anakin Skywalker se rebela contra su mentor, Obi-Wan Kenobi, y se convierte en Darth Vader.",
                            IdDirector = 2,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMzk2NDEzYjAtMGNhZC00MjAyLWFjNjctYWQwNDgyNzg3YTFkXkEyXkFqcGdeQXVyODIyOTEyMzY@._V1_FMjpg_UX816_.jpg",
                            Name = "Star wars: episodio III",
                            Origin = "Internacional"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Amadeo es un chico tímido y virtuoso que deberá enfrentarse a un habilidoso rival sobre el campo de fútbol, conocido con el apodo de El Crack. Para ello, contará con la inestimable ayuda de unos jugadores de futbolín liderados por el Wing, un carismático extremo derecho. Las aventuras de Amadeo y los jugadores tendrán como telón de fondo no solo el fútbol, sino también el amor, la amistad y la pasión.",
                            IdDirector = 3,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTEzMjY1OTM5NjVeQTJeQWpwZ15BbWU3MDcyMjU2NTk@._V1_FMjpg_UY1969_.jpg",
                            Name = "Metegol",
                            Origin = "Nacional"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Un juez tiene dudas acerca de los planes de un oficial de justicia recientemente retirado que intenta descubrir al culpable de la violación y el asesinato de una joven, crimen ocurrido varias décadas atrás.",
                            IdDirector = 3,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMTk0NTYzNjEyOF5BMl5BanBnXkFtZTcwOTAwMDk2Mw@@._V1_FMjpg_UX352_.jpg",
                            Name = "El secreto de sus ojos",
                            Origin = "Nacional"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Rafael Belvedere piensa que las cosas deberían irle mejor. Dedica las veinticuatro horas del día al restaurante fundado por su padre, carga con un divorcio, no se ha tomado el tiempo suficiente para ver crecer a su hija, no tiene amigos y prefiere eludir un mayor compromiso con su novia. Además, hace más de un año que no visita a su madre, que sufre el mal de Alzheimer y está internada en un geriátrico.",
                            IdDirector = 3,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BZDk2OTkxYmItZTc5Ni00YjI0LTg4M2YtN2Y2NjRhYTA4NTA4XkEyXkFqcGdeQXVyMTU3NDU4MDg2._V1_FMjpg_UX1070_.jpg",
                            Name = "El hijo de la novia",
                            Origin = "Nacional"
                        },
                        new
                        {
                            Id = 10,
                            Description = "El club social Luna de Avellaneda está amenazado de ser transformado en un casino a causa de la crisis económica en Argentina. Román, uno de los más antiguos miembros del club, luchará para mantenerlo.",
                            IdDirector = 3,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BMjA5NTM3NTkzN15BMl5BanBnXkFtZTcwNzAzNDMzMQ@@._V1_FMjpg_UX279_.jpg",
                            Name = "Luna de avellaneda",
                            Origin = "Nacional"
                        });
                });

            modelBuilder.Entity("Domain.Entities.MovieScreening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilmId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdFilm")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("MoviesScreening");
                });

            modelBuilder.Entity("Domain.Entities.Film", b =>
                {
                    b.HasOne("Domain.Entities.Director", "Director")
                        .WithMany()
                        .HasForeignKey("IdDirector")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Domain.Entities.MovieScreening", b =>
                {
                    b.HasOne("Domain.Entities.Film", "Film")
                        .WithMany()
                        .HasForeignKey("FilmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Film");
                });
#pragma warning restore 612, 618
        }
    }
}
